[package]
name = "minimusic"
version = "0.1.0"
authors = ["Maya Hayden <mayahayden@protonmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.4.0"
indicatif = { version = "0.15.0", features = ["rayon"]}
structopt = "0.3.17"
regex = "1.3.9"
